export interface Country {
    code: string
    nameES: string
    nameEN: string
    flag: string
    dialCode: string
}

export const COUNTRIES: Country[] = [
    // Latin America & Caribbean
    { code: 'UY', nameES: 'Uruguay', nameEN: 'Uruguay', flag: '🇺🇾', dialCode: '+598' },
    { code: 'AR', nameES: 'Argentina', nameEN: 'Argentina', flag: '🇦🇷', dialCode: '+54' },
    { code: 'BR', nameES: 'Brasil', nameEN: 'Brazil', flag: '🇧🇷', dialCode: '+55' },
    { code: 'CL', nameES: 'Chile', nameEN: 'Chile', flag: '🇨🇱', dialCode: '+56' },
    { code: 'PY', nameES: 'Paraguay', nameEN: 'Paraguay', flag: '🇵🇾', dialCode: '+595' },
    { code: 'BO', nameES: 'Bolivia', nameEN: 'Bolivia', flag: '🇧🇴', dialCode: '+591' },
    { code: 'PE', nameES: 'Perú', nameEN: 'Peru', flag: '🇵🇪', dialCode: '+51' },
    { code: 'EC', nameES: 'Ecuador', nameEN: 'Ecuador', flag: '🇪🇨', dialCode: '+593' },
    { code: 'CO', nameES: 'Colombia', nameEN: 'Colombia', flag: '🇨🇴', dialCode: '+57' },
    { code: 'VE', nameES: 'Venezuela', nameEN: 'Venezuela', flag: '🇻🇪', dialCode: '+58' },
    { code: 'MX', nameES: 'México', nameEN: 'Mexico', flag: '🇲🇽', dialCode: '+52' },
    { code: 'GT', nameES: 'Guatemala', nameEN: 'Guatemala', flag: '🇬🇹', dialCode: '+502' },
    { code: 'BZ', nameES: 'Belice', nameEN: 'Belize', flag: '🇧🇿', dialCode: '+501' },
    { code: 'SV', nameES: 'El Salvador', nameEN: 'El Salvador', flag: '🇸🇻', dialCode: '+503' },
    { code: 'HN', nameES: 'Honduras', nameEN: 'Honduras', flag: '🇭🇳', dialCode: '+504' },
    { code: 'NI', nameES: 'Nicaragua', nameEN: 'Nicaragua', flag: '🇳🇮', dialCode: '+505' },
    { code: 'CR', nameES: 'Costa Rica', nameEN: 'Costa Rica', flag: '🇨🇷', dialCode: '+506' },
    { code: 'PA', nameES: 'Panamá', nameEN: 'Panama', flag: '🇵🇦', dialCode: '+507' },
    { code: 'CU', nameES: 'Cuba', nameEN: 'Cuba', flag: '🇨🇺', dialCode: '+53' },
    { code: 'DO', nameES: 'República Dominicana', nameEN: 'Dominican Republic', flag: '🇩🇴', dialCode: '+1' },
    { code: 'HT', nameES: 'Haití', nameEN: 'Haiti', flag: '🇭🇹', dialCode: '+509' },
    { code: 'JM', nameES: 'Jamaica', nameEN: 'Jamaica', flag: '🇯🇲', dialCode: '+1' },
    { code: 'TT', nameES: 'Trinidad y Tobago', nameEN: 'Trinidad and Tobago', flag: '🇹🇹', dialCode: '+1' },
    { code: 'BB', nameES: 'Barbados', nameEN: 'Barbados', flag: '🇧🇧', dialCode: '+1' },
    { code: 'GY', nameES: 'Guyana', nameEN: 'Guyana', flag: '🇬🇾', dialCode: '+592' },
    { code: 'SR', nameES: 'Surinam', nameEN: 'Suriname', flag: '🇸🇷', dialCode: '+597' },
    { code: 'PR', nameES: 'Puerto Rico', nameEN: 'Puerto Rico', flag: '🇵🇷', dialCode: '+1' },

    // North America
    { code: 'US', nameES: 'Estados Unidos', nameEN: 'United States', flag: '🇺🇸', dialCode: '+1' },
    { code: 'CA', nameES: 'Canadá', nameEN: 'Canada', flag: '🇨🇦', dialCode: '+1' },

    // Europe
    { code: 'ES', nameES: 'España', nameEN: 'Spain', flag: '🇪🇸', dialCode: '+34' },
    { code: 'PT', nameES: 'Portugal', nameEN: 'Portugal', flag: '🇵🇹', dialCode: '+351' },
    { code: 'FR', nameES: 'Francia', nameEN: 'France', flag: '🇫🇷', dialCode: '+33' },
    { code: 'IT', nameES: 'Italia', nameEN: 'Italy', flag: '🇮🇹', dialCode: '+39' },
    { code: 'DE', nameES: 'Alemania', nameEN: 'Germany', flag: '🇩🇪', dialCode: '+49' },
    { code: 'GB', nameES: 'Reino Unido', nameEN: 'United Kingdom', flag: '🇬🇧', dialCode: '+44' },
    { code: 'IE', nameES: 'Irlanda', nameEN: 'Ireland', flag: '🇮🇪', dialCode: '+353' },
    { code: 'NL', nameES: 'Países Bajos', nameEN: 'Netherlands', flag: '🇳🇱', dialCode: '+31' },
    { code: 'BE', nameES: 'Bélgica', nameEN: 'Belgium', flag: '🇧🇪', dialCode: '+32' },
    { code: 'CH', nameES: 'Suiza', nameEN: 'Switzerland', flag: '🇨🇭', dialCode: '+41' },
    { code: 'AT', nameES: 'Austria', nameEN: 'Austria', flag: '🇦🇹', dialCode: '+43' },
    { code: 'SE', nameES: 'Suecia', nameEN: 'Sweden', flag: '🇸🇪', dialCode: '+46' },
    { code: 'NO', nameES: 'Noruega', nameEN: 'Norway', flag: '🇳🇴', dialCode: '+47' },
    { code: 'DK', nameES: 'Dinamarca', nameEN: 'Denmark', flag: '🇩🇰', dialCode: '+45' },
    { code: 'FI', nameES: 'Finlandia', nameEN: 'Finland', flag: '🇫🇮', dialCode: '+358' },
    { code: 'PL', nameES: 'Polonia', nameEN: 'Poland', flag: '🇵🇱', dialCode: '+48' },
    { code: 'CZ', nameES: 'República Checa', nameEN: 'Czech Republic', flag: '🇨🇿', dialCode: '+420' },
    { code: 'SK', nameES: 'Eslovaquia', nameEN: 'Slovakia', flag: '🇸🇰', dialCode: '+421' },
    { code: 'HU', nameES: 'Hungría', nameEN: 'Hungary', flag: '🇭🇺', dialCode: '+36' },
    { code: 'RO', nameES: 'Rumania', nameEN: 'Romania', flag: '🇷🇴', dialCode: '+40' },
    { code: 'BG', nameES: 'Bulgaria', nameEN: 'Bulgaria', flag: '🇧🇬', dialCode: '+359' },
    { code: 'GR', nameES: 'Grecia', nameEN: 'Greece', flag: '🇬🇷', dialCode: '+30' },
    { code: 'HR', nameES: 'Croacia', nameEN: 'Croatia', flag: '🇭🇷', dialCode: '+385' },
    { code: 'RS', nameES: 'Serbia', nameEN: 'Serbia', flag: '🇷🇸', dialCode: '+381' },
    { code: 'SI', nameES: 'Eslovenia', nameEN: 'Slovenia', flag: '🇸🇮', dialCode: '+386' },
    { code: 'RU', nameES: 'Rusia', nameEN: 'Russia', flag: '🇷🇺', dialCode: '+7' },
    { code: 'UA', nameES: 'Ucrania', nameEN: 'Ukraine', flag: '🇺🇦', dialCode: '+380' },
    { code: 'TR', nameES: 'Turquía', nameEN: 'Turkey', flag: '🇹🇷', dialCode: '+90' },
    { code: 'LV', nameES: 'Letonia', nameEN: 'Latvia', flag: '🇱🇻', dialCode: '+371' },
    { code: 'LT', nameES: 'Lituania', nameEN: 'Lithuania', flag: '🇱🇹', dialCode: '+370' },
    { code: 'EE', nameES: 'Estonia', nameEN: 'Estonia', flag: '🇪🇪', dialCode: '+372' },
    { code: 'IS', nameES: 'Islandia', nameEN: 'Iceland', flag: '🇮🇸', dialCode: '+354' },
    { code: 'LU', nameES: 'Luxemburgo', nameEN: 'Luxembourg', flag: '🇱🇺', dialCode: '+352' },
    { code: 'MT', nameES: 'Malta', nameEN: 'Malta', flag: '🇲🇹', dialCode: '+356' },
    { code: 'CY', nameES: 'Chipre', nameEN: 'Cyprus', flag: '🇨🇾', dialCode: '+357' },
    { code: 'AL', nameES: 'Albania', nameEN: 'Albania', flag: '🇦🇱', dialCode: '+355' },
    { code: 'MK', nameES: 'Macedonia del Norte', nameEN: 'North Macedonia', flag: '🇲🇰', dialCode: '+389' },
    { code: 'BA', nameES: 'Bosnia y Herzegovina', nameEN: 'Bosnia and Herzegovina', flag: '🇧🇦', dialCode: '+387' },
    { code: 'ME', nameES: 'Montenegro', nameEN: 'Montenegro', flag: '🇲🇪', dialCode: '+382' },
    { code: 'MD', nameES: 'Moldavia', nameEN: 'Moldova', flag: '🇲🇩', dialCode: '+373' },
    { code: 'BY', nameES: 'Bielorrusia', nameEN: 'Belarus', flag: '🇧🇾', dialCode: '+375' },

    // Middle East
    { code: 'IL', nameES: 'Israel', nameEN: 'Israel', flag: '🇮🇱', dialCode: '+972' },
    { code: 'SA', nameES: 'Arabia Saudita', nameEN: 'Saudi Arabia', flag: '🇸🇦', dialCode: '+966' },
    { code: 'AE', nameES: 'Emiratos Árabes Unidos', nameEN: 'United Arab Emirates', flag: '🇦🇪', dialCode: '+971' },
    { code: 'QA', nameES: 'Qatar', nameEN: 'Qatar', flag: '🇶🇦', dialCode: '+974' },
    { code: 'KW', nameES: 'Kuwait', nameEN: 'Kuwait', flag: '🇰🇼', dialCode: '+965' },
    { code: 'BH', nameES: 'Baréin', nameEN: 'Bahrain', flag: '🇧🇭', dialCode: '+973' },
    { code: 'OM', nameES: 'Omán', nameEN: 'Oman', flag: '🇴🇲', dialCode: '+968' },
    { code: 'JO', nameES: 'Jordania', nameEN: 'Jordan', flag: '🇯🇴', dialCode: '+962' },
    { code: 'LB', nameES: 'Líbano', nameEN: 'Lebanon', flag: '🇱🇧', dialCode: '+961' },
    { code: 'IQ', nameES: 'Irak', nameEN: 'Iraq', flag: '🇮🇶', dialCode: '+964' },
    { code: 'IR', nameES: 'Irán', nameEN: 'Iran', flag: '🇮🇷', dialCode: '+98' },
    { code: 'YE', nameES: 'Yemen', nameEN: 'Yemen', flag: '🇾🇪', dialCode: '+967' },

    // Asia
    { code: 'JP', nameES: 'Japón', nameEN: 'Japan', flag: '🇯🇵', dialCode: '+81' },
    { code: 'CN', nameES: 'China', nameEN: 'China', flag: '🇨🇳', dialCode: '+86' },
    { code: 'KR', nameES: 'Corea del Sur', nameEN: 'South Korea', flag: '🇰🇷', dialCode: '+82' },
    { code: 'IN', nameES: 'India', nameEN: 'India', flag: '🇮🇳', dialCode: '+91' },
    { code: 'ID', nameES: 'Indonesia', nameEN: 'Indonesia', flag: '🇮🇩', dialCode: '+62' },
    { code: 'PH', nameES: 'Filipinas', nameEN: 'Philippines', flag: '🇵🇭', dialCode: '+63' },
    { code: 'TH', nameES: 'Tailandia', nameEN: 'Thailand', flag: '🇹🇭', dialCode: '+66' },
    { code: 'VN', nameES: 'Vietnam', nameEN: 'Vietnam', flag: '🇻🇳', dialCode: '+84' },
    { code: 'MY', nameES: 'Malasia', nameEN: 'Malaysia', flag: '🇲🇾', dialCode: '+60' },
    { code: 'SG', nameES: 'Singapur', nameEN: 'Singapore', flag: '🇸🇬', dialCode: '+65' },
    { code: 'HK', nameES: 'Hong Kong', nameEN: 'Hong Kong', flag: '🇭🇰', dialCode: '+852' },
    { code: 'TW', nameES: 'Taiwán', nameEN: 'Taiwan', flag: '🇹🇼', dialCode: '+886' },
    { code: 'PK', nameES: 'Pakistán', nameEN: 'Pakistan', flag: '🇵🇰', dialCode: '+92' },
    { code: 'BD', nameES: 'Bangladés', nameEN: 'Bangladesh', flag: '🇧🇩', dialCode: '+880' },
    { code: 'LK', nameES: 'Sri Lanka', nameEN: 'Sri Lanka', flag: '🇱🇰', dialCode: '+94' },
    { code: 'NP', nameES: 'Nepal', nameEN: 'Nepal', flag: '🇳🇵', dialCode: '+977' },
    { code: 'MM', nameES: 'Myanmar', nameEN: 'Myanmar', flag: '🇲🇲', dialCode: '+95' },
    { code: 'KH', nameES: 'Camboya', nameEN: 'Cambodia', flag: '🇰🇭', dialCode: '+855' },
    { code: 'LA', nameES: 'Laos', nameEN: 'Laos', flag: '🇱🇦', dialCode: '+856' },
    { code: 'MN', nameES: 'Mongolia', nameEN: 'Mongolia', flag: '🇲🇳', dialCode: '+976' },
    { code: 'KZ', nameES: 'Kazajistán', nameEN: 'Kazakhstan', flag: '🇰🇿', dialCode: '+7' },
    { code: 'UZ', nameES: 'Uzbekistán', nameEN: 'Uzbekistan', flag: '🇺🇿', dialCode: '+998' },
    { code: 'AZ', nameES: 'Azerbaiyán', nameEN: 'Azerbaijan', flag: '🇦🇿', dialCode: '+994' },
    { code: 'GE', nameES: 'Georgia', nameEN: 'Georgia', flag: '🇬🇪', dialCode: '+995' },
    { code: 'AM', nameES: 'Armenia', nameEN: 'Armenia', flag: '🇦🇲', dialCode: '+374' },
    { code: 'AF', nameES: 'Afganistán', nameEN: 'Afghanistan', flag: '🇦🇫', dialCode: '+93' },

    // Africa
    { code: 'EG', nameES: 'Egipto', nameEN: 'Egypt', flag: '🇪🇬', dialCode: '+20' },
    { code: 'ZA', nameES: 'Sudáfrica', nameEN: 'South Africa', flag: '🇿🇦', dialCode: '+27' },
    { code: 'NG', nameES: 'Nigeria', nameEN: 'Nigeria', flag: '🇳🇬', dialCode: '+234' },
    { code: 'KE', nameES: 'Kenia', nameEN: 'Kenya', flag: '🇰🇪', dialCode: '+254' },
    { code: 'ET', nameES: 'Etiopía', nameEN: 'Ethiopia', flag: '🇪🇹', dialCode: '+251' },
    { code: 'GH', nameES: 'Ghana', nameEN: 'Ghana', flag: '🇬🇭', dialCode: '+233' },
    { code: 'TZ', nameES: 'Tanzania', nameEN: 'Tanzania', flag: '🇹🇿', dialCode: '+255' },
    { code: 'TN', nameES: 'Túnez', nameEN: 'Tunisia', flag: '🇹🇳', dialCode: '+216' },
    { code: 'MA', nameES: 'Marruecos', nameEN: 'Morocco', flag: '🇲🇦', dialCode: '+212' },
    { code: 'DZ', nameES: 'Argelia', nameEN: 'Algeria', flag: '🇩🇿', dialCode: '+213' },
    { code: 'LY', nameES: 'Libia', nameEN: 'Libya', flag: '🇱🇾', dialCode: '+218' },
    { code: 'SN', nameES: 'Senegal', nameEN: 'Senegal', flag: '🇸🇳', dialCode: '+221' },
    { code: 'CI', nameES: 'Costa de Marfil', nameEN: 'Ivory Coast', flag: '🇨🇮', dialCode: '+225' },
    { code: 'CM', nameES: 'Camerún', nameEN: 'Cameroon', flag: '🇨🇲', dialCode: '+237' },
    { code: 'UG', nameES: 'Uganda', nameEN: 'Uganda', flag: '🇺🇬', dialCode: '+256' },
    { code: 'RW', nameES: 'Ruanda', nameEN: 'Rwanda', flag: '🇷🇼', dialCode: '+250' },
    { code: 'MZ', nameES: 'Mozambique', nameEN: 'Mozambique', flag: '🇲🇿', dialCode: '+258' },
    { code: 'ZM', nameES: 'Zambia', nameEN: 'Zambia', flag: '🇿🇲', dialCode: '+260' },
    { code: 'ZW', nameES: 'Zimbabue', nameEN: 'Zimbabwe', flag: '🇿🇼', dialCode: '+263' },
    { code: 'AO', nameES: 'Angola', nameEN: 'Angola', flag: '🇦🇴', dialCode: '+244' },
    { code: 'MG', nameES: 'Madagascar', nameEN: 'Madagascar', flag: '🇲🇬', dialCode: '+261' },
    { code: 'MU', nameES: 'Mauricio', nameEN: 'Mauritius', flag: '🇲🇺', dialCode: '+230' },
    { code: 'SD', nameES: 'Sudán', nameEN: 'Sudan', flag: '🇸🇩', dialCode: '+249' },

    // Oceania
    { code: 'AU', nameES: 'Australia', nameEN: 'Australia', flag: '🇦🇺', dialCode: '+61' },
    { code: 'NZ', nameES: 'Nueva Zelanda', nameEN: 'New Zealand', flag: '🇳🇿', dialCode: '+64' },
    { code: 'PG', nameES: 'Papúa Nueva Guinea', nameEN: 'Papua New Guinea', flag: '🇵🇬', dialCode: '+675' },
    { code: 'FJ', nameES: 'Fiyi', nameEN: 'Fiji', flag: '🇫🇯', dialCode: '+679' },
]

// Sorted alphabetically by nameES for default display
export const COUNTRIES_ES = [...COUNTRIES].sort((a, b) => a.nameES.localeCompare(b.nameES, 'es'))
export const COUNTRIES_EN = [...COUNTRIES].sort((a, b) => a.nameEN.localeCompare(b.nameEN, 'en'))

export function getCountryByCode(code: string): Country | undefined {
    return COUNTRIES.find(c => c.code === code)
}

export function getPhonePlaceholder(dialCode: string): string {
    const placeholders: Record<string, string> = {
        '+598': '99 123 456',
        '+54': '11 1234 5678',
        '+55': '11 9 1234 5678',
        '+56': '9 1234 5678',
        '+595': '981 123 456',
        '+591': '7 123 4567',
        '+51': '987 654 321',
        '+593': '98 765 4321',
        '+57': '300 123 4567',
        '+58': '412 123 4567',
        '+52': '55 1234 5678',
        '+1': '(555) 123-4567',
        '+34': '612 34 56 78',
        '+351': '912 345 678',
        '+33': '06 12 34 56 78',
        '+39': '312 345 6789',
        '+49': '170 1234567',
        '+44': '07700 900123',
        '+31': '06 12345678',
        '+32': '0470 12 34 56',
        '+41': '076 123 45 67',
        '+46': '070-123 45 67',
        '+47': '400 12 345',
        '+45': '20 12 34 56',
        '+358': '040 123 4567',
        '+7': '912 345-67-89',
        '+81': '90-1234-5678',
        '+86': '131 2345 6789',
        '+82': '010-1234-5678',
        '+91': '98765 43210',
        '+971': '050 123 4567',
        '+966': '050 123 4567',
        '+61': '0412 345 678',
        '+64': '021 123 4567',
        '+27': '071 123 4567',
    }
    return placeholders[dialCode] ?? '123 456 789'
}
